spring:
  application:
    name: admin
  profiles:
    include: common
    active: prod
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
lpsouti:
  default-user:
    username: admin
    email: admin@lpsouti.com
    password: lpsouti666